language: go
go:
- 1.8
- 1.9
sudo: false
addons:
  postgresql: '9.5'
services:
- postgres
- docker
env:
  matrix:
  - LIBRDKAFKA_VERSION=v0.11.4
  - LIBRDKAFKA_VERSION=master
cache:
  directories:
  - "$HOME/.cache/librdkafka"
before_install:
- sudo /bin/bash ./travis.sh
before_script: make setup-ci
script: make test
